### ISSUE TITLE
Make announcement center an official app

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/announcementcenter#46] opened 2016-02-24 08:49 UTC
During a upgrade just now I got "Disabled apps: announcement center (3rd party app)".

is this correct? @karlitschek @nickvergessen

**Comment by nickvergessen** [comment] 2016-02-24 09:05
Well in 8.2 it was not an official app, but it is in 9.0 so from that on it should not get disabled anymore. cc @LukasReschke

**Comment by MorrisJobke** [comment] 2016-02-24 09:16
This was an upgrade from 9.0.0 master yesterday to master today (test of the tag column switch from int to string)

**Comment by nickvergessen** [comment] 2016-02-24 09:23
Okay right, the appstore says the app is official, but it's not in shipped.json which is checked on update.

The problem is, if we add it there, community people (where the app is not shipped) will have a problem, because for them the app needs to be disabled on update and then grab the new version from the appstore.

**Comment by MorrisJobke** [comment] 2016-02-24 09:27
> The problem is, if we add it there, community people (where the app is not shipped)

Why is it not shipped in the community version? :confused: - @karlitschek

**Comment by nickvergessen** [comment] 2016-02-24 09:39
Because we don't want to ship everything?
It's in the app store, the only reason why it is shipped in EE is because we don't support the appstore there yet. See https://github.com/owncloud/core/issues/19152#issuecomment-160918312 and following

**Comment by MorrisJobke** [comment] 2016-02-24 09:56
> Because we don't want to ship everything?

Then we need to check our core logic - announcing an official app as 3rdparty during update and then disable it sounds totally weird.

**Comment by karlitschek** [comment] 2016-02-24 12:17
in the future webhave to avoid the situation that an app is in the tar in EE and in rhe app store in CE. this is weird. too late to change the logic now before 9.0 so we have lot keep it for now. in the future we only should have obe way to distribute one app.

**Comment by nickvergessen** [comment] 2016-02-24 12:43
So closing, as 
> is this correct?

Is indeed correct.

**Closed by nickvergessen** 2016-02-24 12:43 UTC
Labels: question
